### ISSUE TITLE
CSS不定高宽度元素水平垂直居中

### ISSUE THREAD

**Issue by XXHolic** [XXHolic/blog#4]
# CSS不定高宽度元素水平垂直居中
## 想法
在[CSS居中初级理解](https://github.com/XXHolic/blog/issues/3)里面分别对水平和垂直居中做了一些总结，举例用的元素有固定高宽度，不定高宽度元素同时水平垂直居中的需求，也比较常见，很自然的想到，将水平和垂直的方法相结合应该就可以达到效果，的确是可以这样，结合后效果有时跟预想的不太一样，本文主要就是对这种“不太一样”再想一下。
## 约定
这里更多的是去理解规范，在这里就不会去比较它们的优劣和兼容性。居中效果需要有一个参照物，下面CSS实现方法前提是，都有一个一定高度和宽度的父元素。不定宽高元素使用属性display:inline-block,元素的高宽度由文本撑起，以下统称居中元素。html的基本结构如下：
```html
<div class="css-center-parent-rec">
  <div class="css-center-auto-rec">给我撑起给我撑起给我撑起给我撑起给我撑起</div>
</div>
```
基本CSS属性如下：
```css
.css-center-parent-rec{
  margin-bottom: 10px;
  border: 1px solid #333;
  width: 300px;
  height: 186px;
}
.css-center-auto-rec {
  display: inline-block;
  border: 1px solid #333;
}
```
#### 方法1：使用table布局
这种方法需要额外的标签，形成跟table标签类似的结构，调整后结构如下
```html
<div class="css-center-parent-rec dt">
  <div class="css-center-auto-rec-wrap dtc">
    <div class="css-center-auto-rec">给我撑起给我撑起给我撑起给我撑起给我撑起</div>
  </div>
</div>
```
新增的css如下：
```css
/* 添加到父元素上 */
.dt {
  display: table;
}
/* 额外的元素 */
.dtc {
  display: table-cell;
}
.css-center-auto-rec-wrap {
  vertical-align: middle;
  text-align: center;
}
```
这种方法就是水平居中方法2和垂直居中方法1中vertical属性，结合到一起，就有了同时水平垂直居中的效果。居中元素宽度超过父元素可用宽度时会换行。对应水平和垂直居中方法见[CSS居中初级理解](https://github.com/XXHolic/blog/issues/3)。
#### 方法2：行内块法
```css
/* 添加到父元素上 */
.tc {
  text-align: center;
}
.css-center-auto-parent-rec {
  font-size: 0;
}
.css-center-auto-parent-rec:before {
  content: "";
  display: inline-block;
  height: 100%;
  vertical-align: middle;
}
/* 添加到居中元素上 */
.vam {
  vertical-align: middle;
}
.fb {
  font-size: 14px;
}
```
这种方法就是水平居中方法2和垂直居中方法1，结合到一起，就有了同时水平垂直居中的效果。居中元素宽度超过父元素可用宽度时会换行。对应水平和垂直居中方法见[CSS居中初级理解](https://github.com/XXHolic/blog/issues/3)。
#### 方法3：使用定位position和transform
```css
/* 添加到父元素上 */
.pr {
  position: relative;
}
/* 添加到居中元素上 */
.css-center-auto-pos {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
}
```
这种方法是水平居中方法4和垂直居中方法3，结合到一起，但这种方式有2种现象：
1. 居中元素宽度没有超过视觉上父元素可用宽度就会换行。
2. 如果有边框会明显的边框变粗或文字模糊。

关于现象1，在计算宽度和边距说明文档[calculating widths and margins](https://www.w3.org/TR/CSS22/visudet.html#Computing_widths_and_margins)里面，可以找到这种情况是第七种情形：绝对定位非替换元素。
> 7. absolutely positioned, non-replaced elements

计算的时候会遵循一个约束规则：
> 'left' + 'margin-left' + 'border-left-width' + 'padding-left' + 'width' + 'padding-right' + 'border-right-width' + 'margin-right' + 'right' = width of containing block

由于box-sizing的属性值为border-box，该元素的边框和内边距都会在width内绘制，所以公式里面的width包含了边框和内边距的宽度，居中元素绝对定位偏移相对于内边距边界（padding edge），不包含border，所以计算left百分比的宽度是300-2=298px,最后套用公式后变成如下：  
  298px * 50% + 0 + auto + 0 + auto = 298px  
这种情况就是width和right为auto，left不是auto，那么width就会渲染成适当的尺寸，right的值也就会得出。width适当尺寸限制是不会超过可用的宽度值，这里可用的宽度值为298-298*50% = 149px,所以只要超过了149px就会换行。  

关于现象2，这个在最新的浏览器里面，ie、火狐都是正常的，谷歌和safari就会出现这样的问题，这个经过查询和尝试，结果是当计算转换后，值是基数的时候渲染才会有问题，偶数的时候没有问题，在transform值matrix中有0.5px小数时，在谷歌和safari渲染会出问题，为什么会这样，目前个人还不清楚，但可以用js取近似值解决这个问题，视觉上一般觉察不到。
```javascript
function roundCssTransformMatrix(element){
  var el = document.getElementById(element);
  //gets the current computed style
  var mx = window.getComputedStyle(el, null); 
  //resets the redifined matrix to allow recalculation, the original style should be defined in the class not inline.
  el.style.transform=""; 
  mx = mx.getPropertyValue("-webkit-transform") ||
    mx.getPropertyValue("-moz-transform") ||
    mx.getPropertyValue("-ms-transform") ||
    mx.getPropertyValue("-o-transform") ||
    mx.getPropertyValue("transform") || false;
  var values = mx.replace(/ |\(|\)|matrix/g,"").split(",");
  for(var v in values) {  values[v]=Math.ceil(values[v]);  }
  el.style.webkitTransform = "matrix("+values.join()+")";
}

```
#### 方法4：使用flex布局
```css
/* 添加到父元素上 */
.df {
  display: flex;
}
/* 添加到居中元素上 */
.css-center-auto-flex {
  justify-content: center;
  align-items: center;
}
```
这种方法就是水平居中方法5和垂直居中方法4，结合到一起，就有了同时水平垂直居中的效果。居中元素宽度超过父元素可用宽度时会换行。对应水平和垂直居中方法见[CSS居中初级理解](https://github.com/XXHolic/blog/issues/3)。

以上方法示例链接：https://xxholic.github.io/lab/lab-css/css-center-auto.html

## 参考相关
- Definition of "containing block"：https://www.w3.org/TR/CSS22/visudet.html#containing-block-details
- Chrome Font appears Blurry：https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry
